### PR TITLE
Throws IllegalStateException when trying to rewrite InputStreamBlob.

### LINKED ISSUE #103: Throw IllegalStateException when trying to rewrite InputStreamBlob.
`InputStreamBlobs` should only be allowed to be written out once (it closes the `InputStream`).

### PR DESCRIPTION
**Pull request by coollog**
Fixes #103

### CODE REVIEW

File: crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java [hunk 1]
```diff
@@ -19,6 +19,10 @@
 import java.io.IOException;
 import java.io.OutputStream;
 
+/**
+ * Function that writes the contents of a BLOB. This functions should write the same BLOB regardless
```
Comment (elharo) [inline crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java]: This function

File: crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java [hunk 2]
```diff
@@ -19,6 +19,10 @@
...
+ * of the number of times it is called.
```
Comment (elharo) [inline crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java]: Isn't the point of this that it can only be called once?

Comment (coollog) [reply crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java]: `FileBlob`, `StringBlob`, and `WriterBlob` should all be able to be written out more than once. However, `InputStreamBlob` is tied to a read-once InputStream, so it can only be written out once.

File: crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java [hunk 3]
```diff
@@ -19,6 +19,10 @@
 import java.io.IOException;
 import java.io.OutputStream;
 
+/**
+ * This function that writes the contents of a BLOB. This functions should write the same BLOB
```
Comment (elharo) [inline crepecake/src/main/java/com/google/cloud/tools/crepecake/blob/BlobWriter.java]: functions --> function
